### ISSUE TITLE
Laravel 6+ and PHP 7.4

### ISSUE THREAD

**Issue by omidMolaverdi** [Laragear/CacheQuery#20]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

Dear Author,

This is a package that shines. 

Can you please make it compatible with PHP 7.4 and Laravel 6+?

### Code sample

```php
PHP 7.4
DB::table('user')->cache(30,'id_123')->get();
```

**Comment by DarkGhostHunter** [comment]
Thanks for the compliment!

To keep the support active and refactoring minimal, all Laragear packages only support the latest stable PHP and Laravel versions.

I would recommend you to fork this library and refactor it for older platforms.
