### ISSUE TITLE
Add support to cache non sql code

### ISSUE THREAD

**Issue by sefirosweb** [Laragear/CacheQuery#32]
### Please check these requirements

- [X] This feature helps everyone using this package
- [X] It's feasible and maintainable
- [X] It's non breaking
- [ ] I issued a PR with the implementation (optional)

### Description

Hello i have a custom connector in laravel, but this connecto dont use a "query" has string, the query is a "array" of elements,

In your code needs to be string, this is easy to improve adding a JSON_ENCODE in code

https://github.com/Laragear/CacheQuery/blob/377a8706c8433f171fb2883a644efb01470ae7fa/src/CacheAwareConnectionProxy.php#L106-L109

### Code sample

```php
protected function getQueryHash($query, array $bindings): string
    {
        return rtrim(base64_encode(md5($this->connection->getDatabaseName() . json_encode($query) . implode('', $bindings), true)), '=');
    }
```

**Comment by DarkGhostHunter** [comment]
I could rather let the user register a function to create the query hash, being the default... the default.

**Comment by sefirosweb** [comment]
Ah, yes true, that makes more sense, so I can create my own function that generates the hash, and override the behavior.

**Comment by DarkGhostHunter** [comment]
Added that in [v4.1.0](https://github.com/Laragear/CacheQuery/releases/tag/v4.1.0).
