### ISSUE TITLE
[1.x] Forgetting a key returns Array to String exception

### ISSUE THREAD

**Issue by wit3** [Laragear/CacheQuery#9]
### PHP & Platform

8.1.3

### Laravel verion

9.17.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can reproduce this bug in isolation (vanilla Laravel install)
- [ ] I can suggest a workaround as a Pull Request

### Expectation

Forget key programmatically with Facade

```
CacheQuery::forget('offer_details_distinct_quadro');
```

or 

with artisan command thrown exception

### Description

Array to string exception

### Reproduction

```php
$arrayOption = Model::query()->cache(key: 'offer_details_distinct_quadro', ttl: now()->addHour())->distinct()->pluck('name', 'name')
```

### Stack trace & logs

```shell
ErrorException 

  Array to string conversion

  at vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php:223
    219▕      * @return bool
    220▕      */
    221▕     public function forget($key)
    222▕     {
  ➜ 223▕         return (bool) $this->connection()->del($this->prefix.$key);
    224▕     }
    225▕ 
    226▕     /**
    227▕      * Remove all items from the cache.

      +18 vendor frames
```

### Are you a Patreon supporter?

No, don't give priority to this

**Comment by DarkGhostHunter** [comment]
Fixed in #31b736742816eeb6b901d5ccd4fdd069a7e9d4bb, patch incoming in 5 min.
